"""Shadowrocket INI Configuration Compiler (shadowrocket.conf).

Produces complete, fine-grained routing configuration for iOS Shadowrocket:
- Strict C2 implementation: udp-policy-not-supported-behaviour = REJECT (prevents real IP leaks)
- Prepend QUIC block rule: AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT
- Pure domestic DNS resolution (223.5.5.5, 119.29.29.29)
- Dynamic policy groups matching regions.json without hardcoded airport names
- Uses Rule Intermediate Representation (IR) to cleanly resolve all targets (zero @ residue)
Zero third-party dependencies: 100% Python 3 standard library.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from proxymatrix.model import (
    GROUP_AI,
    GROUP_AUTO,
    GROUP_DIRECT,
    GROUP_GOOGLE,
    GROUP_MEDIA,
    GROUP_PROXY,
    GROUP_REJECT,
    RegionDefinition,
    Rule,
    load_regions,
    parse_rule_string,
)

# Canonical Shadowrocket group names for clean INI output
SR_GROUP_NAMES = {
    GROUP_PROXY: "PROXY",
    GROUP_DIRECT: "DIRECT",
    GROUP_REJECT: "REJECT",
    GROUP_AI: "AI Services",
    GROUP_GOOGLE: "Google Services",
    GROUP_MEDIA: "Streaming Media",
    "@region_hk": "Hong Kong",
    "@region_jp": "Japan",
    "@region_us": "United States",
    "@region_sg": "Singapore",
    "@region_tw": "Taiwan",
    "@region_kr": "Korea",
    "@region_uk": "United Kingdom",
    "@region_de": "Germany",
}


def compile_shadowrocket_conf(
    root_dir: Path,
    custom_sites: Optional[List[Dict[str, Any]]] = None,
    dns_preset: str = "cn-mainland"
) -> str:
    """Compile complete shadowrocket.conf INI text."""
    config_dir = root_dir / "config"
    rules_dir = root_dir / "rules"

    regions = load_regions(config_dir / "regions.json")

    # 1. Build [General] section
    dns_servers = "223.5.5.5, 119.29.29.29" if dns_preset == "cn-mainland" else "1.1.1.1, 8.8.8.8"
    dns_direct = "true" if dns_preset == "cn-mainland" else "false"

    general_lines = [
        "[General]",
        "# Generated by ProxyMatrix",
        "bypass-system = true",
        "skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, *.crashlytics.com",
        "tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32",
        f"dns-server = {dns_servers}",
        f"dns-direct-system = {dns_direct}",
        "ipv6 = false",
        "update-url = ",
        "# Strict leak prevention: Reject unroutable UDP to force fallback",
        "udp-policy-not-supported-behaviour = REJECT",
        "",
    ]

    # 2. Build [Rule] section using Rule IR
    rule_lines = [
        "[Rule]",
        "# Prepend QUIC block to force graceful fallback to TCP TLS",
        "AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT",
    ]

    # Custom sites
    if custom_sites:
        for site in custom_sites:
            if not site.get("enabled", True):
                continue
            domain = site.get("domain")
            kind = site.get("type", "DOMAIN-SUFFIX")
            target_id = site.get("group") or site.get("target") or GROUP_PROXY
            r = Rule(type=kind, payload=domain, target_id=target_id)
            sr_rule = r.to_shadowrocket_rule(SR_GROUP_NAMES)
            if sr_rule:
                for line in sr_rule.splitlines():
                    rule_lines.append(line)

    # Core rules via Rule IR
    rules_file = rules_dir / "rules.json"
    if rules_file.is_file():
        with open(rules_file, "r", encoding="utf-8") as f:
            raw_rules = json.load(f)
        for r_str in raw_rules:
            rule = parse_rule_string(r_str)
            sr_rule = rule.to_shadowrocket_rule(SR_GROUP_NAMES)
            if sr_rule:
                for line in sr_rule.splitlines():
                    rule_lines.append(line)

    # 3. Build [Proxy Group] section dynamically
    group_lines = [
        "",
        "[Proxy Group]",
        "# Built-in Service Groups",
        'AI Services = select, policy-regex-filter=(?:美国|US|USA|日本|JP|新加坡|SG)',
        'Google Services = select, policy-regex-filter=(?:美国|US|USA|日本|JP|香港|HK)',
        'Streaming Media = select, policy-regex-filter=(?:香港|HK|台湾|TW|日本|JP|新加坡|SG)',
        "",
        "# Dynamic Region Groups",
    ]

    for r in regions:
        sr_name = SR_GROUP_NAMES.get(r.id, r.display_name)
        # Note: Shadowrocket policy-regex-filter forbids '=' in regex
        clean_regex = r.regex_pattern.replace("=", "")
        group_lines.append(f"{sr_name} = select, policy-regex-filter={clean_regex}")

    # Assemble full INI
    return "\n".join(general_lines + rule_lines + group_lines) + "\n"
