"""Shadowrocket INI Configuration Compiler (shadowrocket.conf).

Produces complete, fine-grained routing configuration for iOS Shadowrocket:
- Strict C2 implementation: udp-policy-not-supported-behaviour = REJECT (prevents real IP leaks)
- Prepend QUIC block rule: AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT
- Pure domestic DNS resolution (223.5.5.5, 119.29.29.29)
- Dynamic policy groups matching regions.json without hardcoded airport names
- Uses Rule Intermediate Representation (IR) to cleanly resolve all targets (zero @ residue)
Zero third-party dependencies: 100% Python 3 standard library.
"""

from dataclasses import dataclass, field
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from proxymatrix.model import (
    GROUP_AI,
    GROUP_AUTO,
    GROUP_DIRECT,
    GROUP_GOOGLE,
    GROUP_MEDIA,
    GROUP_PROXY,
    GROUP_REJECT,
    RegionDefinition,
    Rule,
    load_regions,
    parse_rule_string,
)

# Canonical Shadowrocket group names for clean INI output
SR_GROUP_NAMES = {
    GROUP_PROXY: "PROXY",
    GROUP_DIRECT: "DIRECT",
    GROUP_REJECT: "REJECT",
    GROUP_AI: "AI Services",
    GROUP_GOOGLE: "Google Services",
    GROUP_MEDIA: "Streaming Media",
    "@region_hk": "Hong Kong",
    "@region_jp": "Japan",
    "@region_us": "United States",
    "@region_sg": "Singapore",
    "@region_tw": "Taiwan",
    "@region_kr": "Korea",
    "@region_uk": "United Kingdom",
    "@region_de": "Germany",
}


@dataclass
class LossyConversionReport:
    """Detailed record of dropped, degraded, and transformed routing rules."""
    total_rules: int = 0
    emitted_rules: int = 0
    dropped_rules: List[Dict[str, str]] = field(default_factory=list)
    converted_rules: List[Dict[str, str]] = field(default_factory=list)
    policy_notes: List[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Render human-readable Markdown summary of lossy conversions."""
        lines = [
            "# Shadowrocket 规则转换与有损降级报告 (Lossy Conversion Report)",
            "",
            "本报告记录从 Clash / Mihomo 规则集编译为 iOS Shadowrocket 配置时的降级转换、标签展开与静默丢弃项。",
            "",
            "## 1. 规则统计概览",
            f"- **输入规则总数**: {self.total_rules} 条",
            f"- **有效生成规则**: {self.emitted_rules} 条",
            f"- **转换/展开规则**: {len(self.converted_rules)} 条",
            f"- **静默丢弃规则**: {len(self.dropped_rules)} 条",
            "",
            "## 2. 丢弃规则清单 (Dropped Rules)",
        ]
        if self.dropped_rules:
            lines.extend([
                "| 原始规则 | 目标策略 | 处理原因与替代方案 |",
                "| :--- | :--- | :--- |",
            ])
            for d in self.dropped_rules:
                lines.append(f"| `{d['rule']}` | `{d['target']}` | {d['reason']} |")
        else:
            lines.append("无规则被丢弃。")

        lines.extend([
            "",
            "## 3. 降级与展开规则清单 (Converted / Degraded Rules)",
        ])
        if self.converted_rules:
            lines.extend([
                "| 原始规则 | 转换后规则 | 转换说明 |",
                "| :--- | :--- | :--- |",
            ])
            for c in self.converted_rules:
                lines.append(f"| `{c['original']}` | `{c['converted']}` | {c['reason']} |")
        else:
            lines.append("无规则被转换或降级。")

        lines.extend([
            "",
            "## 4. 关键策略差异与安全保障说明",
        ])
        for note in self.policy_notes:
            lines.append(f"- {note}")

        return "\n".join(lines) + "\n"


def compile_shadowrocket_conf(
    root_dir: Path,
    custom_sites: Optional[List[Dict[str, Any]]] = None,
    dns_preset: str = "cn-mainland",
    report: Optional[LossyConversionReport] = None,
) -> str:
    """Compile complete shadowrocket.conf INI text and optionally record lossy report."""
    config_dir = root_dir / "config"
    rules_dir = root_dir / "rules"

    regions = load_regions(config_dir / "regions.json")

    if report is not None:
        report.policy_notes = [
            "UDP 旁路防泄露: udp-policy-not-supported-behaviour = REJECT (防止非代理 UDP 直连泄露客户端真实 IP)。",
            "QUIC 强制拦截: AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT (强制 HTTP/3 回退至 TCP TLS，提升分流稳定性)。",
            "内网绕行与私有网段展开: GEOSITE,private 虽丢弃，但已由 skip-proxy、tun-excluded-routes 及自动展开的私有 IP-CIDR 段全量承接。",
            "国内流量防境外代理泄露: GEOSITE,cn 虽被丢弃，但已由 DOMAIN-SUFFIX,cn 及移除 no-resolve 启用本地 DNS 解析的 GEOIP,CN 规则联合承接，确保淘宝、京东等国内流量直连，避免误入海外代理。",
            "策略组类型转换: Clash url-test 自动选优在 Shadowrocket 中编译为带正则过滤的 select 策略组。",
        ]

    # 1. Build [General] section
    dns_servers = "223.5.5.5, 119.29.29.29" if dns_preset == "cn-mainland" else "1.1.1.1, 8.8.8.8"
    dns_direct = "true" if dns_preset == "cn-mainland" else "false"

    general_lines = [
        "[General]",
        "# Generated by ProxyMatrix",
        "bypass-system = true",
        "skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, *.crashlytics.com",
        "tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32",
        f"dns-server = {dns_servers}",
        f"dns-direct-system = {dns_direct}",
        "ipv6 = false",
        "update-url = ",
        "# Strict leak prevention: Reject unroutable UDP to force fallback",
        "udp-policy-not-supported-behaviour = REJECT",
        "",
    ]

    # 2. Build [Rule] section using Rule IR
    rule_lines = [
        "[Rule]",
        "# Prepend QUIC block to force graceful fallback to TCP TLS",
        "AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT",
    ]

    # Custom sites
    if custom_sites:
        for site in custom_sites:
            if report is not None:
                report.total_rules += 1
            if not site.get("enabled", True):
                if report is not None:
                    report.dropped_rules.append({
                        "rule": f"{site.get('type', 'DOMAIN-SUFFIX')},{site.get('domain', '')}",
                        "target": site.get("group") or site.get("target") or "@proxy",
                        "reason": "规则在控制台被禁用 (enabled: false)",
                    })
                continue
            domain = site.get("domain")
            kind = site.get("type", "DOMAIN-SUFFIX")
            target_id = site.get("group") or site.get("target") or GROUP_PROXY
            r = Rule(type=kind, payload=domain, target_id=target_id)
            sr_rule = r.to_shadowrocket_rule(SR_GROUP_NAMES)
            if sr_rule:
                for line in sr_rule.splitlines():
                    rule_lines.append(line)
                    if report is not None:
                        report.emitted_rules += 1
            elif report is not None:
                report.dropped_rules.append({
                    "rule": f"{kind},{domain}",
                    "target": target_id,
                    "reason": f"Shadowrocket 不支持 {kind} 规则；已丢弃",
                })

    # Core rules via Rule IR
    rules_file = rules_dir / "rules.json"
    if rules_file.is_file():
        with open(rules_file, "r", encoding="utf-8") as f:
            raw_rules = json.load(f)
        for r_str in raw_rules:
            if report is not None:
                report.total_rules += 1
            rule = parse_rule_string(r_str)
            sr_rule = rule.to_shadowrocket_rule(SR_GROUP_NAMES)
            if sr_rule:
                for line in sr_rule.splitlines():
                    rule_lines.append(line)
                    if report is not None:
                        report.emitted_rules += 1
                if report is not None:
                    if rule.type == "GEOSITE" and rule.payload == "google":
                        report.converted_rules.append({
                            "original": r_str,
                            "converted": sr_rule.replace("\n", " / "),
                            "reason": "Shadowrocket 不支持 GEOSITE 标签；展开为明确的 DOMAIN-SUFFIX 规则",
                        })
                    elif rule.type == "GEOIP" and rule.payload.upper() == "PRIVATE":
                        report.converted_rules.append({
                            "original": r_str,
                            "converted": "IP-CIDR,10.0.0.0/8,... (展开为多段私有 CIDR)",
                            "reason": "Shadowrocket 不支持 GEOIP,private；自动展开为 RFC 1918 与本地私有 IPv4/IPv6 CIDR 段",
                        })
                    elif rule.type == "GEOIP" and rule.payload.upper() == "CN":
                        report.converted_rules.append({
                            "original": r_str,
                            "converted": "DOMAIN-SUFFIX,cn,DIRECT / GEOIP,CN,DIRECT",
                            "reason": "追加 DOMAIN-SUFFIX,cn 并移除 no-resolve 启用本地 DNS 解析，防止国内域名回退至海外代理",
                        })
                    elif r_str.startswith("MATCH,") or r_str.startswith("FINAL,"):
                        report.converted_rules.append({
                            "original": r_str,
                            "converted": sr_rule,
                            "reason": "Clash MATCH 终态分流转为 Shadowrocket FINAL 指令",
                        })
            else:
                if report is not None:
                    reason = f"Shadowrocket 不支持 {rule.type} 规则；已丢弃"
                    if rule.type == "GEOSITE":
                        if rule.payload == "private":
                            reason = "Shadowrocket 不支持私有 GEOSITE 标签；已在 skip-proxy 与展开后的私有 IP-CIDR 规则中全量兜底"
                        elif rule.payload == "cn":
                            reason = "Shadowrocket 不支持 GEOSITE 标签；国内流量已由 DOMAIN-SUFFIX,cn 与本地解析后的 GEOIP,CN 联合接管"
                        else:
                            reason = f"Shadowrocket 不支持 GEOSITE,{rule.payload} 标签；已丢弃"
                    report.dropped_rules.append({
                        "rule": r_str,
                        "target": rule.target_id,
                        "reason": reason,
                    })

    # 3. Build [Proxy Group] section dynamically
    group_lines = [
        "",
        "[Proxy Group]",
        "# Built-in Service Groups",
        'AI Services = select, include-all-proxies=true, policy-regex-filter=(?:美国|US|USA|日本|JP|新加坡|SG)',
        'Google Services = select, include-all-proxies=true, policy-regex-filter=(?:美国|US|USA|日本|JP|香港|HK)',
        'Streaming Media = select, include-all-proxies=true, policy-regex-filter=(?:香港|HK|台湾|TW|日本|JP|新加坡|SG)',
        "",
        "# Dynamic Region Groups",
    ]

    for r in regions:
        sr_name = SR_GROUP_NAMES.get(r.id, r.display_name)
        # Note: Shadowrocket policy-regex-filter forbids '=' in regex
        clean_regex = r.regex_pattern.replace("=", "")
        group_lines.append(f"{sr_name} = select, include-all-proxies=true, policy-regex-filter={clean_regex}")

    # Assemble full INI
    return "\n".join(general_lines + rule_lines + group_lines) + "\n"
